# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /habitacion
            logout:
                path: /logout
                target: /
